(function(name,data){
 if(typeof onTileMapLoaded === 'undefined') {
  if(typeof TileMaps === 'undefined') TileMaps = {};
  TileMaps[name] = data;
 } else {
  onTileMapLoaded(name,data);
 }
 if(typeof module === 'object' && module && module.exports) {
  module.exports = data;
 }})("mapRealfagsbygget",
{ "compressionlevel":-1,
 "height":20,
 "infinite":true,
 "layers":[
        {
         "chunks":[
                {
                 "data":"AQAAAAIAAAADAAAABAAAAAUAAAAGAAAABwAAAAgAAAAJAAAACgAAAAsAAAAMAAAADQAAAA4AAAAPAAAAEAAAACAAAAAhAAAAIgAAACMAAAAkAAAAJQAAACYAAAAnAAAAKAAAACkAAAAqAAAAKwAAACwAAAAtAAAALgAAAC8AAAA\/AAAAQAAAAEEAAABCAAAAQwAAAEQAAABFAAAARgAAAEcAAABIAAAASQAAAEoAAABLAAAATAAAAE0AAABOAAAAXgAAAF8AAABgAAAAYQAAAGIAAABjAAAAZAAAAGUAAABmAAAAZwAAAGgAAABpAAAAagAAAGsAAABsAAAAbQAAAH0AAAB+AAAAfwAAAIAAAACBAAAAggAAAIMAAACEAAAAhQAAAIYAAACHAAAAiAAAAIkAAACKAAAAiwAAAIwAAACcAAAAnQAAAJ4AAACfAAAAoAAAAKEAAACiAAAAowAAAKQAAAClAAAApgAAAKcAAACoAAAAqQAAAKoAAACrAAAAuwAAALwAAAC9AAAAvgAAAL8AAADAAAAAwQAAAMIAAADDAAAAxAAAAMUAAADGAAAAxwAAAMgAAADJAAAAygAAANoAAADbAAAA3AAAAN0AAADeAAAA3wAAAOAAAADhAAAA4gAAAOMAAADkAAAA5QAAAOYAAADnAAAA6AAAAOkAAAD5AAAA+gAAAPsAAAD8AAAA\/QAAAP4AAAD\/AAAAAAEAAAEBAAACAQAAAwEAAAQBAAAFAQAABgEAAAcBAAAIAQAAGAEAABkBAAAaAQAAGwEAABwBAAAdAQAAHgEAAB8BAAAgAQAAIQEAACIBAAAjAQAAJAEAACUBAAAmAQAAJwEAADcBAAA4AQAAOQEAADoBAAA7AQAAPAEAAD0BAAA+AQAAPwEAAEABAABBAQAAQgEAAEMBAABEAQAARQEAAEYBAABWAQAAVwEAAFgBAABZAQAAWgEAAFsBAABcAQAAXQEAAF4BAABfAQAAYAEAAGEBAABiAQAAYwEAAGQBAABlAQAAdQEAAHYBAAB3AQAAeAEAAHkBAAB6AQAAewEAAHwBAAB9AQAAfgEAAH8BAACAAQAAgQEAAIIBAACDAQAAhAEAAJQBAACVAQAAlgEAAJcBAACYAQAAmQEAAJoBAACbAQAAnAEAAJ0BAACeAQAAnwEAAKABAAChAQAAogEAAKMBAACzAQAAtAEAALUBAAC2AQAAtwEAALgBAAC5AQAAugEAALsBAAC8AQAAvQEAAL4BAAC\/AQAAwAEAAMEBAADCAQAA0gEAANMBAADUAQAA1QEAANYBAADXAQAA2AEAANkBAADaAQAA2wEAANwBAADdAQAA3gEAAN8BAADgAQAA4QEAAA==",
                 "height":16,
                 "width":16,
                 "x":-16,
                 "y":-16
                }, 
                {
                 "data":"EQAAABIAAAATAAAAFAAAABUAAAAWAAAAFwAAABgAAAAZAAAAGgAAABsAAAAcAAAAHQAAAB4AAAAfAAAADQIAADAAAAAxAAAAMgAAADMAAAA0AAAANQAAADYAAAA3AAAAOAAAADkAAAA6AAAAOwAAADwAAAA9AAAAPgAAAA0CAABPAAAAUAAAAFEAAABSAAAAUwAAAFQAAABVAAAAVgAAAFcAAABYAAAAWQAAAFoAAABbAAAAXAAAAF0AAAANAgAAbgAAAG8AAABwAAAAcQAAAHIAAABzAAAAdAAAAHUAAAB2AAAAdwAAAHgAAAB5AAAAegAAAHsAAAB8AAAADQIAAI0AAACOAAAAjwAAAJAAAACRAAAAkgAAAJMAAACUAAAAlQAAAJYAAACXAAAAmAAAAJkAAACaAAAAmwAAAA0CAACsAAAArQAAAK4AAACvAAAAsAAAALEAAACyAAAAswAAALQAAAC1AAAAtgAAALcAAAC4AAAAuQAAALoAAAANAgAAywAAAMwAAADNAAAAzgAAAM8AAADQAAAA0QAAANIAAADTAAAA1AAAANUAAADWAAAA1wAAANgAAADZAAAADQIAAOoAAADrAAAA7AAAAO0AAADuAAAA7wAAAPAAAADxAAAA8gAAAPMAAAD0AAAA9QAAAPYAAAD3AAAA+AAAAA0CAAAJAQAACgEAAAsBAAAMAQAADQEAAA4BAAAoAgAAKAIAABEBAAASAQAAEwEAABQBAAAVAQAAFgEAABcBAAANAgAAKAEAACkBAAAqAQAAKwEAACwBAAAtAQAAKAIAACgCAAAwAQAAMQEAADIBAAAzAQAANAEAADUBAAA2AQAADQIAAEcBAABIAQAASQEAAEoBAABLAQAATAEAAE0BAABOAQAATwEAAFABAABRAQAAUgEAAFMBAABUAQAAVQEAAA0CAABmAQAAZwEAAGgBAABpAQAAagEAAGsBAABsAQAAbQEAAG4BAABvAQAAcAEAAHEBAAByAQAAcwEAAHQBAAANAgAAhQEAAIYBAACHAQAAiAEAAIkBAACKAQAAiwEAAIwBAACNAQAAjgEAAI8BAACQAQAAkQEAAJIBAACTAQAADQIAAKQBAAClAQAApgEAAKcBAACoAQAAqQEAAKoBAACrAQAArAEAAK0BAACuAQAArwEAALABAACxAQAAsgEAAA0CAADDAQAAxAEAAMUBAADGAQAAxwEAAMgBAADJAQAAygEAAMsBAADMAQAAzQEAAM4BAADPAQAA0AEAANEBAABVAQAA4gEAAOMBAADkAQAA5QEAAOYBAADnAQAA6AEAAOkBAADqAQAA6wEAAOwBAADtAQAA7gEAAO8BAADwAQAAdAEAAA==",
                 "height":16,
                 "width":16,
                 "x":0,
                 "y":-16
                }, 
                {
                 "data":"8QEAAPIBAADzAQAA9AEAAPUBAAD2AQAA9wEAAPgBAAD5AQAA+gEAAPsBAAD8AQAA\/QEAAP4BAAD\/AQAAAAIAABACAAARAgAAEgIAABMCAAAUAgAAFQIAABYCAAAXAgAAGAIAABkCAAAaAgAAGwIAABwCAAAdAgAAHgIAAB8CAAAvAgAAMAIAADECAAAyAgAAMwIAADQCAAA1AgAANgIAADcCAAA4AgAAOQIAADoCAAA7AgAAPAIAAD0CAAA+AgAATgIAAE8CAABQAgAAUQIAAFICAABTAgAAVAIAAFUCAABWAgAAVwIAAFgCAABZAgAAWgIAAFsCAABcAgAAXQIAAG0CAABuAgAAbwIAAHACAABxAgAAcgIAAHMCAAB0AgAAdQIAAHYCAAB3AgAAeAIAAHkCAAB6AgAAewIAAHwCAACMAgAAjQIAAI4CAACPAgAAkAIAAJECAACSAgAAkwIAAJQCAACVAgAAlgIAAJcCAACYAgAAmQIAAJoCAACbAgAAqwIAAKwCAACtAgAArgIAAK8CAACwAgAAsQIAALICAACzAgAAtAIAALUCAAC2AgAAtwIAALgCAAC5AgAAugIAAMoCAADLAgAAzAIAAM0CAADOAgAAzwIAANACAADRAgAA0gIAANMCAADUAgAA1QIAANYCAADXAgAA2AIAANkCAADpAgAA6gIAAOsCAADsAgAA7QIAAO4CAADvAgAA8AIAAPECAADyAgAA8wIAAPQCAAD1AgAA9gIAAPcCAAD4AgAADQIAAIwCAACNAgAAjgIAAI8CAACQAgAAkQIAAJICAACTAgAAlAIAAJUCAACWAgAADQIAAA0CAAANAgAADQIAAA0CAACrAgAArAIAAK0CAACuAgAArwIAALACAACxAgAAsgIAALMCAAC0AgAAtQIAALYCAAC3AgAAuAIAALkCAAANAgAAygIAAMsCAADMAgAAzQIAAM4CAADPAgAA0AIAANECAADSAgAA0wIAANQCAADVAgAA1gIAAA0CAAANAgAADQIAAOkCAADqAgAA6wIAAOwCAADtAgAA7gIAAO8CAADwAgAA8QIAAPICAADzAgAA9AIAAPUCAAD2AgAA9wIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
                 "height":16,
                 "width":16,
                 "x":-16,
                 "y":0
                }, 
                {
                 "data":"AQIAAAICAAADAgAABAIAAAUCAAAGAgAABwIAAAgCAAAJAgAACgIAAAsCAAAMAgAADQIAAA4CAAAPAgAAkwEAACACAAAhAgAAIgIAACMCAAAkAgAAJQIAACYCAAAnAgAAKAIAACkCAAAqAgAAKwIAACwCAAAtAgAALgIAALIBAAA\/AgAAQAIAAEECAABCAgAAQwIAAEQCAABFAgAARgIAAEcCAABIAgAASQIAAEoCAABLAgAATAIAAE0CAADRAQAAXgIAAF8CAABgAgAAYQIAAGICAABjAgAAZAIAAGUCAABmAgAAZwIAAGgCAABpAgAAagIAAGsCAABsAgAA8AEAAH0CAAB+AgAAfwIAAIACAACBAgAAggIAAIMCAACEAgAAhQIAAIYCAACHAgAAiAIAAIkCAACKAgAAiwIAAA8CAACcAgAAnQIAAJ4CAACfAgAAoAIAAKECAACiAgAAowIAAKQCAAClAgAApgIAAKcCAACoAgAAqQIAAKoCAAAuAgAAuwIAALwCAAC9AgAAvgIAAL8CAADAAgAAwQIAAMICAADDAgAAxAIAAMUCAADGAgAAxwIAAMgCAADJAgAATQIAANoCAADbAgAA3AIAAN0CAADeAgAA3wIAAOACAADhAgAA4gIAAOMCAADkAgAA5QIAAOYCAADnAgAA6AIAAGwCAAD5AgAA+gIAAPsCAAD8AgAA\/QIAAP4CAAD\/AgAAAAMAAAEDAAACAwAAAwMAAAQDAAAFAwAABgMAAAcDAACLAgAADQIAAA0CAAANAgAADQIAAA0CAAANAgAADQIAAA0CAAANAgAADQIAAA0CAAANAgAADQIAAKgCAACpAgAAqgIAALoCAAC7AgAAvAIAAL0CAAC+AgAAvwIAAMACAAANAgAADQIAAA0CAAANAgAADQIAAA0CAADHAgAAyAIAAMkCAAANAgAADQIAAA0CAADcAgAA3QIAAN4CAADfAgAA4AIAAOECAAANAgAADQIAAA0CAAANAgAA5gIAAOcCAADoAgAA+AIAAPkCAAD6AgAADQIAAA0CAAANAgAADQIAAA0CAAANAgAADQIAAA0CAAANAgAABAMAAAUDAAAGAwAABwMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
                 "height":16,
                 "width":16,
                 "x":0,
                 "y":0
                }],
         "compression":"",
         "encoding":"base64",
         "height":64,
         "id":1,
         "name":"Rutelag 1",
         "opacity":1,
         "startx":-32,
         "starty":-32,
         "type":"tilelayer",
         "visible":true,
         "width":80,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "id":3,
         "name":"Objektlag 1",
         "objects":[
                {
                 "class":"",
                 "height":226.666666666667,
                 "id":14,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":25.9999999999999,
                 "x":-537.333333333333,
                 "y":-533.333333333333
                }, 
                {
                 "class":"",
                 "height":22,
                 "id":15,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":128.666666666667,
                 "x":-535.333333333333,
                 "y":-534.666666666667
                }, 
                {
                 "class":"",
                 "height":194,
                 "id":16,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":23.3333333333333,
                 "x":-425.333333333333,
                 "y":-534.666666666667
                }, 
                {
                 "class":"",
                 "height":26.6666666666667,
                 "id":18,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":94,
                 "x":-425.333333333333,
                 "y":-367.333333333333
                }, 
                {
                 "class":"",
                 "height":194,
                 "id":19,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":22,
                 "x":-353.333333333333,
                 "y":-536
                }, 
                {
                 "class":"",
                 "height":24,
                 "id":20,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":126.666666666667,
                 "x":-352,
                 "y":-536.666666666667
                }, 
                {
                 "class":"",
                 "height":194.666666666667,
                 "id":21,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":26,
                 "x":-250.666666666667,
                 "y":-536
                }, 
                {
                 "class":"",
                 "height":22,
                 "id":22,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":107.270833333333,
                 "x":-249.729166666667,
                 "y":-363.333333333333
                }, 
                {
                 "class":"",
                 "height":191.333333333333,
                 "id":23,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":23.3333333333333,
                 "x":-164.666666666667,
                 "y":-532.666666666667
                }, 
                {
                 "class":"",
                 "height":20.6666666666666,
                 "id":24,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":123.333333333333,
                 "x":-164.666666666667,
                 "y":-532.666666666667
                }, 
                {
                 "class":"",
                 "height":170.666666666667,
                 "id":25,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":23.3333333333333,
                 "x":-64.6666666666667,
                 "y":-512
                }, 
                {
                 "class":"",
                 "height":24.6666666666667,
                 "id":26,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":104,
                 "x":-64,
                 "y":-366
                }, 
                {
                 "class":"",
                 "height":162.666666666667,
                 "id":27,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":22.6666666666667,
                 "x":17.3333333333333,
                 "y":-523.333333333333
                }, 
                {
                 "class":"",
                 "height":19.3333333333334,
                 "id":28,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":122,
                 "x":16,
                 "y":-532.666666666667
                }, 
                {
                 "class":"",
                 "height":192,
                 "id":29,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":26.6666666666667,
                 "x":120,
                 "y":-532.666666666667
                }, 
                {
                 "class":"",
                 "height":19.5833333333334,
                 "id":30,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":100.67,
                 "x":119.999033816425,
                 "y":-360
                },
            
                {
                 "class":"",
                 "height":190,
                 "id":31,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":18.6666666666667,
                 "x":202,
                 "y":-530.666666666667
                }, 
                {
                 "class":"",
                 "height":18,
                 "id":32,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":122.666666666667,
                 "x":202,
                 "y":-530.666666666667
                }, 
                {
                 "class":"",
                 "height":173.771739130435,
                 "id":33,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":23.3333333333333,
                 "x":301.333333333333,
                 "y":-514.916666666667
                }, 
                {
                 "class":"",
                 "height":20.3125,
                 "id":34,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":66,
                 "x":301.333333333333,
                 "y":-360.666666666667
                }, 
                {
                 "class":"",
                 "height":135.333333333333,
                 "id":35,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":16,
                 "x":351.333333333333,
                 "y":-488.666666666667
                }, 
                {
                 "class":"",
                 "height":17.3333333333333,
                 "id":36,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":152.666666666667,
                 "x":351.333333333333,
                 "y":-488.666666666667
                }, 
                {
                 "class":"",
                 "height":295.333333333333,
                 "id":37,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":24,
                 "x":480.666666666667,
                 "y":-486.666666666667
                }, 
                {
                 "class":"",
                 "height":11.3333333333333,
                 "id":38,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":151.333333333333,
                 "x":352.666666666667,
                 "y":-203.333333333333
                }, 
                {
                 "class":"",
                 "height":18.5,
                 "id":56,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":147,
                 "x":-368,
                 "y":7.75
                }, 
                {
                 "class":"",
                 "height":42.5,
                 "id":57,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":21.75,
                 "x":-232.25,
                 "y":-14
                }, 
                {
                 "class":"",
                 "height":31.25,
                 "id":58,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":64.75,
                 "x":-224,
                 "y":-45
                }, 
                {
                 "class":"",
                 "height":194,
                 "id":59,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":24,
                 "x":-183,
                 "y":-44
                }, 
                {
                 "class":"",
                 "height":37,
                 "id":60,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":15,
                 "x":355,
                 "y":-232
                }, 
                {
                 "class":"",
                 "height":23,
                 "id":62,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":110.67,
                 "x":255.333333333333,
                 "y":-232
                }, 
                {
                 "class":"",
                 "height":22.6666666666667,
                 "id":65,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":51.3333333333333,
                 "x":140.333333333333,
                 "y":-231.666666666667
                }, 
                {
                 "class":"",
                 "height":15,
                 "id":66,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":113,
                 "x":36.3333333333333,
                 "y":-228
                },
            
                {
                 "class":"",
                 "height":10,
                 "id":67,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":66.3333333333333,
                 "x":-25.3333333333333,
                 "y":-228.333333333333
                }, 
                {
                 "class":"",
                 "height":14.3333333333333,
                 "id":68,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":135.666666666667,
                 "x":-157.666666666667,
                 "y":-228
                }, 
                {
                 "class":"",
                 "height":25,
                 "id":69,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":28.3333333333333,
                 "x":-157.666666666667,
                 "y":-232.333333333333
                }, 
                {
                 "class":"",
                 "height":11.6666666666666,
                 "id":70,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":64.3333333333333,
                 "x":-537.666666666667,
                 "y":-310.666666666667
                }, 
                {
                 "class":"",
                 "height":71,
                 "id":71,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":11,
                 "x":-484.333333333333,
                 "y":-310.666666666667
                }, 
                {
                 "class":"",
                 "height":32.2666666666667,
                 "id":76,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":17.7111111111112,
                 "x":-345.333333333333,
                 "y":-251.933333333333
                }, 
                {
                 "class":"",
                 "height":16.2727272727273,
                 "id":77,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":157.375,
                 "x":-485,
                 "y":-251.939393939394
                }, 
                {
                 "class":"",
                 "height":22,
                 "id":80,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":160,
                 "x":-430.333333333333,
                 "y":-223
                }, 
                {
                 "class":"",
                 "height":20,
                 "id":82,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":120.5,
                 "x":-187,
                 "y":140
                }, 
                {
                 "class":"",
                 "height":77,
                 "id":83,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":13.5,
                 "x":-80,
                 "y":83.5
                }, 
                {
                 "class":"",
                 "height":15,
                 "id":84,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":55.5,
                 "x":-80,
                 "y":83.5
                }, 
                {
                 "class":"",
                 "height":90,
                 "id":86,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":15,
                 "x":-39,
                 "y":84
                }, 
                {
                 "class":"",
                 "height":14,
                 "id":87,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":92,
                 "x":-39.5,
                 "y":168
                }, 
                {
                 "class":"",
                 "height":92.5,
                 "id":88,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":15,
                 "x":37,
                 "y":83.5
                }, 
                {
                 "class":"",
                 "height":13,
                 "id":89,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":56.5,
                 "x":37,
                 "y":83.5
                }, 
                {
                 "class":"",
                 "height":94.5,
                 "id":90,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":12.5,
                 "x":80.5,
                 "y":83.5
                },
            
                {
                 "class":"",
                 "height":14.5,
                 "id":91,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":104,
                 "x":80,
                 "y":168
                }, 
                {
                 "class":"",
                 "height":99,
                 "id":92,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":12.5,
                 "x":172,
                 "y":83
                }, 
                {
                 "class":"",
                 "height":13.5,
                 "id":93,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":68.4555555555555,
                 "x":172.044444444444,
                 "y":83
                }, 
                {
                 "class":"",
                 "height":124,
                 "id":94,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":15,
                 "x":225.5,
                 "y":83
                }, 
                {
                 "class":"",
                 "height":10,
                 "id":95,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":34.5,
                 "x":224,
                 "y":197.5
                }, 
                {
                 "class":"",
                 "height":90.5,
                 "id":97,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":13,
                 "x":246,
                 "y":198
                }, 
                {
                 "class":"",
                 "height":11.5,
                 "id":99,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":42.5,
                 "x":244.5,
                 "y":282
                }, 
                {
                 "class":"",
                 "height":13,
                 "id":101,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":71.5,
                 "x":284,
                 "y":288.5
                }, 
                {
                 "class":"",
                 "height":31.625,
                 "id":103,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":16.75,
                 "x":312,
                 "y":163.875
                }, 
                {
                 "class":"",
                 "height":13.875,
                 "id":104,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":42.5,
                 "x":312.25,
                 "y":163.875
                }, 
                {
                 "class":"",
                 "height":92.75,
                 "id":105,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":14.5,
                 "x":342.875,
                 "y":73.125
                }, 
                {
                 "class":"",
                 "height":19.25,
                 "id":106,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":16,
                 "x":346.75,
                 "y":57
                }, 
                {
                 "class":"",
                 "height":20,
                 "id":107,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":13.5,
                 "x":351.75,
                 "y":39.75
                }, 
                {
                 "class":"",
                 "height":21.5,
                 "id":108,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":13.5,
                 "x":356.75,
                 "y":24
                }, 
                {
                 "class":"",
                 "height":19.25,
                 "id":109,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":13,
                 "x":360.75,
                 "y":8.75
                }, 
                {
                 "class":"",
                 "height":18.5,
                 "id":110,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":38.1666666666666,
                 "x":366,
                 "y":-5.25
                },
            
                {
                 "class":"",
                 "height":11,
                 "id":112,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":64,
                 "x":338,
                 "y":-45.5
                }, 
                {
                 "class":"",
                 "height":48.5,
                 "id":113,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":16.5,
                 "x":338,
                 "y":-90
                }, 
                {
                 "class":"",
                 "height":13,
                 "id":115,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":61.5,
                 "x":339.5,
                 "y":-90
                }, 
                {
                 "class":"",
                 "height":16.5,
                 "id":116,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":51.5,
                 "x":389,
                 "y":-102.5
                }, 
                {
                 "class":"",
                 "height":84,
                 "id":118,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":14.6666666666667,
                 "x":427.67,
                 "y":-183.333333333333
                }, 
                {
                 "class":"",
                 "height":39.6041666666667,
                 "id":119,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":11.6666666666667,
                 "x":292.666666666667,
                 "y":-219.333333333333
                }, 
                {
                 "class":"",
                 "height":9.33333333333334,
                 "id":121,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":147.052083333333,
                 "x":292.947916666667,
                 "y":-189
                }, 
                {
                 "class":"",
                 "height":11.5,
                 "id":123,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":108.5,
                 "x":-334,
                 "y":-232
                }, 
                {
                 "class":"",
                 "height":24.5,
                 "id":124,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":54.75,
                 "x":-280.25,
                 "y":-232
                }, 
                {
                 "class":"",
                 "height":160,
                 "id":143,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":15.6666666666666,
                 "x":-431.666666666667,
                 "y":-202.666666666667
                }, 
                {
                 "class":"",
                 "height":16.3333333333333,
                 "id":147,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":67.3333333333333,
                 "x":-430.666666666667,
                 "y":-44.3333333333333
                }, 
                {
                 "class":"",
                 "height":70.6666666666667,
                 "id":148,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":14.3333333333333,
                 "x":-377.666666666667,
                 "y":-44.3333333333333
                }, 
                {
                 "class":"",
                 "height":8.16666666666669,
                 "id":151,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":349.416666666667,
                 "x":-157.666666666667,
                 "y":-232.5
                }, 
                {
                 "class":"",
                 "height":54.3333333333333,
                 "id":152,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":9.33333333333331,
                 "x":400,
                 "y":-45.3333333333333
                }, 
                {
                 "class":"",
                 "height":10.6666666666667,
                 "id":154,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":51.6666666666666,
                 "x":312,
                 "y":192.666666666667
                }, 
                {
                 "class":"",
                 "height":108.333333333333,
                 "id":155,
                 "name":"",
                 "rotation":0,
                 "visible":true,
                 "width":13.3333333333333,
                 "x":350.333333333333,
                 "y":193
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }],
 "nextlayerid":4,
 "nextobjectid":158,
 "orientation":"orthogonal",
 "renderorder":"right-down",
 "tiledversion":"1.9.2",
 "tileheight":32,
 "tilesets":[
        {
         "firstgid":1,
         "source":"Rbygg.tsx"
        }],
 "tilewidth":32,
 "type":"map",
 "version":"1.9",
 "width":30
});