(function (name, data) {
  if (typeof onTileMapLoaded === "undefined") {
    if (typeof TileMaps === "undefined") var TileMaps = {};
    TileMaps[name] = data;
  } else {
    onTileMapLoaded(name, data);
  }
  if (typeof module === "object" && module && module.exports) {
    module.exports = data;
  }
})("mapData", {
  compressionlevel: -1,
  height: 150,
  infinite: true,
  layers: [
    {
      draworder: "topdown",
      id: 6,
      name: "Start",
      objects: [
        {
          height: 90,
          id: 110,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 90,
          x: 1398,
          y: 2150,
        },
      ],
      opacity: 1,
      class: "objectgroup",
      visible: true,
      x: 0,
      y: 0,
    },
    {
      draworder: "topdown",
      id: 2,
      name: "Collisions",
      objects: [
        {
          height: 1031,
          id: 20,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 30,
          x: 655,
          y: 114,
        },
        {
          height: 20,
          id: 21,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 354,
          x: 685,
          y: 114,
        },
        {
          height: 20,
          id: 24,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 148,
          x: 654,
          y: 1145,
        },
        {
          height: 358,
          id: 25,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 30,
          x: 802,
          y: 1145,
        },
        {
          height: 790,
          id: 26,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 30,
          x: 1039,
          y: 114,
        },
        {
          height: 20,
          id: 27,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 519.818181818182,
          x: 1039,
          y: 904,
        },
        {
          height: 790,
          id: 28,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 30,
          x: 1459,
          y: 114,
        },
        {
          height: 20,
          id: 29,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 353,
          x: 1489,
          y: 114,
        },
        {
          height: 790,
          id: 30,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 30,
          x: 1842,
          y: 114,
        },
        {
          height: 20,
          id: 31,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 641,
          x: 1778,
          y: 904,
        },
        {
          height: 790,
          id: 32,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 30,
          x: 2321,
          y: 114,
        },
        {
          height: 20,
          id: 33,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 353,
          x: 2351,
          y: 114,
        },
        {
          height: 790,
          id: 34,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 30,
          x: 2704,
          y: 114,
        },
        {
          height: 20,
          id: 35,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 616,
          x: 2640,
          y: 904,
        },
        {
          height: 790,
          id: 36,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 30,
          x: 3157,
          y: 114,
        },
        {
          height: 20,
          id: 37,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 353,
          x: 3187,
          y: 114,
        },

        {
          height: 790,
          id: 38,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 30,
          x: 3540,
          y: 114,
        },
        {
          height: 790,
          id: 39,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 30,
          x: 3988,
          y: 114,
        },
        {
          height: 20,
          id: 40,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 353,
          x: 4018,
          y: 114,
        },
        {
          height: 790,
          id: 41,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 30,
          x: 4371,
          y: 114,
        },
        {
          height: 20,
          id: 42,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 605,
          x: 3479,
          y: 904,
        },
        {
          height: 20,
          id: 43,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 380,
          x: 4307,
          y: 904,
        },
        {
          height: 136,
          id: 44,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 35,
          x: 4509,
          y: 924,
        },
        {
          height: 596,
          id: 45,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 30,
          x: 4657,
          y: 308,
        },
        {
          height: 20,
          id: 46,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 622,
          x: 4687,
          y: 308,
        },
        {
          height: 1333,
          id: 47,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 30,
          x: 5309,
          y: 308,
        },
        {
          height: 20,
          id: 48,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 970,
          x: 4369,
          y: 1641,
        },
        {
          height: 20,
          id: 50,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 548,
          x: 4152,
          y: 1503,
        },
        {
          height: 122,
          id: 51,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 35,
          x: 4509,
          y: 1381,
        },
        {
          height: 118,
          id: 53,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 30,
          x: 4670,
          y: 1523,
        },
        {
          height: 431,
          id: 54,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 35,
          x: 4334,
          y: 1523,
        },
        {
          height: 20,
          id: 55,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 259,
          x: 4110,
          y: 1954,
        },

        {
          height: 20,
          id: 57,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 1585,
          x: 2266,
          y: 1503,
        },
        {
          height: 20,
          id: 58,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 1167,
          x: 802,
          y: 1503,
        },
        {
          height: 20,
          id: 59,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 874,
          x: 1095,
          y: 1595,
        },
        {
          height: 20,
          id: 60,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 109,
          x: 2266,
          y: 1595,
        },
        {
          height: 72,
          id: 61,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 30,
          x: 2266,
          y: 1523,
        },
        {
          height: 72,
          id: 63,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 30,
          x: 1939,
          y: 1523,
        },
        {
          height: 267,
          id: 64,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 34,
          x: 2375,
          y: 1523,
        },
        {
          height: 431,
          id: 65,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 35,
          x: 3634,
          y: 1523,
        },
        {
          height: 20,
          id: 66,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 780,
          x: 2375,
          y: 1790,
        },
        {
          height: 20,
          id: 67,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 255,
          x: 3379,
          y: 1790,
        },
        {
          height: 20,
          id: 69,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 254,
          x: 3634,
          y: 1954,
        },
        {
          height: 20,
          id: 70,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 355,
          x: 4627,
          y: 2151,
        },
        {
          height: 490,
          id: 71,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 30,
          x: 4952,
          y: 1661,
        },
        {
          height: 160,
          id: 72,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 34,
          x: 4593,
          y: 2151,
        },
        {
          height: 20,
          id: 73,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 1025,
          x: 3815,
          y: 2311,
        },
        {
          height: 158,
          id: 74,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 35,
          x: 3780,
          y: 2311,
        },

        {
          height: 545,
          id: 75,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 35,
          x: 3780,
          y: 2789,
        },
        {
          height: 477,
          id: 79,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 30,
          x: 4840,
          y: 2311,
        },
        {
          height: 20,
          id: 80,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 279,
          x: 4591,
          y: 2788,
        },
        {
          height: 530,
          id: 81,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 30,
          x: 4561,
          y: 2788,
        },
        {
          height: 572,
          id: 83,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 30,
          x: 4423,
          y: 3318,
        },
        {
          height: 20,
          id: 84,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 138,
          x: 4453,
          y: 3318,
        },
        {
          height: 20,
          id: 85,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 377,
          x: 4076,
          y: 3890,
        },
        {
          height: 970,
          id: 86,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 30,
          x: 4076,
          y: 2920,
        },
        {
          height: 20,
          id: 88,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 261,
          x: 3815,
          y: 2920,
        },
        {
          height: 856,
          id: 89,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 34,
          x: 3396,
          y: 2478,
        },
        {
          height: 20,
          id: 90,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 419,
          x: 3396,
          y: 3334,
        },
        {
          height: 20,
          id: 91,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 255,
          x: 3141,
          y: 2478,
        },
        {
          height: 20,
          id: 92,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 258,
          x: 2661,
          y: 2478,
        },
        {
          height: 732,
          id: 93,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 34,
          x: 2627,
          y: 2478,
        },
        {
          height: 413,
          id: 94,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 30,
          x: 2863,
          y: 2922,
        },
        {
          height: 413,
          id: 95,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 30,
          x: 3161,
          y: 2922,
        },

        {
          height: 20,
          id: 96,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 328,
          x: 2863,
          y: 3335,
        },
        {
          height: 20,
          id: 97,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 205,
          x: 3191,
          y: 2922,
        },
        {
          height: 20,
          id: 98,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 202,
          x: 2661,
          y: 2922,
        },
        {
          height: 1061,
          id: 99,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 35,
          x: 2238,
          y: 2149,
        },
        {
          height: 20,
          id: 100,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 423,
          x: 2238,
          y: 3210,
        },
        {
          height: 813,
          id: 101,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 30,
          x: 1065,
          y: 1595,
        },
        {
          height: 174,
          id: 102,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 30,
          x: 1344,
          y: 2408,
        },
        {
          height: 20,
          id: 103,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 279,
          x: 1065,
          y: 2408,
        },
        {
          height: 20,
          id: 104,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 894,
          x: 1344,
          y: 2582,
        },
        {
          height: 20,
          id: 105,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 1158,
          x: 2273,
          y: 2149,
        },
        {
          height: 15,
          id: 111,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 184,
          x: 1118,
          y: 1636,
        },
        {
          height: 10,
          id: 114,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 63,
          x: 1095,
          y: 2159,
        },
        {
          height: 239,
          id: 115,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 10,
          x: 1148,
          y: 2169,
        },
        {
          height: 1,
          id: 116,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 186,
          x: 1235,
          y: 1915,
        },
        {
          height: 1,
          id: 117,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 186,
          x: 1556,
          y: 1915,
        },
        {
          height: 1,
          id: 118,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 186,
          x: 1878,
          y: 1915,
        },

        {
          height: 1,
          id: 119,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 186,
          x: 1556,
          y: 2253,
        },
        {
          height: 1,
          id: 120,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 186,
          x: 1878,
          y: 2253,
        },
        {
          height: 2,
          id: 121,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 132,
          x: 4018,
          y: 279,
        },
        {
          height: 2,
          id: 122,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 132,
          x: 3187,
          y: 279,
        },
        {
          height: 2,
          id: 123,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 132,
          x: 2351,
          y: 279,
        },
        {
          height: 2,
          id: 124,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 132,
          x: 1489,
          y: 279,
        },
        {
          height: 2,
          id: 125,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 132,
          x: 685,
          y: 279,
        },
        {
          height: 10,
          id: 126,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 60,
          x: 979,
          y: 414,
        },
        {
          height: 335,
          id: 127,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 10,
          x: 979,
          y: 424,
        },
        {
          height: 10,
          id: 128,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 60,
          x: 979,
          y: 759,
        },
        {
          height: 10,
          id: 129,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 60,
          x: 1782,
          y: 685,
        },
        {
          height: 261,
          id: 130,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 10,
          x: 1782,
          y: 424,
        },
        {
          height: 10,
          id: 131,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 60,
          x: 1782,
          y: 414,
        },
        {
          height: 10,
          id: 132,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 60,
          x: 685,
          y: 414,
        },
        {
          height: 480.125,
          id: 133,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 10,
          x: 735,
          y: 424,
        },
        {
          height: 10,
          id: 134,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 60,
          x: 685,
          y: 904,
        },

        {
          height: 10,
          id: 136,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 59,
          x: 1489,
          y: 685,
        },
        {
          height: 261,
          id: 137,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 10,
          x: 1538,
          y: 424,
        },
        {
          height: 10,
          id: 138,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 59,
          x: 1489,
          y: 414,
        },
        {
          height: 10,
          id: 139,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 59,
          x: 2645,
          y: 685,
        },
        {
          height: 261,
          id: 140,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 10,
          x: 2645,
          y: 424,
        },
        {
          height: 10,
          id: 141,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 59,
          x: 2645,
          y: 414,
        },
        {
          height: 10,
          id: 142,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 59,
          x: 2351,
          y: 685,
        },
        {
          height: 261,
          id: 143,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 10,
          x: 2400,
          y: 424,
        },
        {
          height: 10,
          id: 144,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 59,
          x: 2351,
          y: 414,
        },
        {
          height: 10,
          id: 151,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 59,
          x: 3481,
          y: 685,
        },
        {
          height: 261,
          id: 152,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 10,
          x: 3481,
          y: 424,
        },
        {
          height: 10,
          id: 153,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 59,
          x: 3481,
          y: 414,
        },
        {
          height: 10,
          id: 154,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 59,
          x: 3187,
          y: 685,
        },
        {
          height: 261,
          id: 155,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 10,
          x: 3236,
          y: 424,
        },
        {
          height: 10,
          id: 156,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 59,
          x: 3187,
          y: 414,
        },
        {
          height: 10,
          id: 157,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 60,
          x: 4311,
          y: 684,
        },

        {
          height: 261,
          id: 158,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 10,
          x: 4311,
          y: 423,
        },
        {
          height: 10,
          id: 159,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 60,
          x: 4311,
          y: 413,
        },
        {
          height: 10,
          id: 160,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 60,
          x: 4018,
          y: 684,
        },
        {
          height: 261,
          id: 161,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 10,
          x: 4068,
          y: 423,
        },
        {
          height: 10,
          id: 162,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 60,
          x: 4018,
          y: 413,
        },
        {
          height: 10,
          id: 163,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 251,
          x: 4687,
          y: 370,
        },
        {
          height: 10,
          id: 164,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 171,
          x: 5138,
          y: 370,
        },
        {
          height: 42,
          id: 165,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 10,
          x: 4928,
          y: 328,
        },
        {
          height: 42,
          id: 167,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 10,
          x: 5138,
          y: 328,
        },
        {
          height: 179,
          id: 168,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 164,
          x: 4879,
          y: 881,
        },
        {
          height: 10,
          id: 169,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 164,
          x: 5145,
          y: 633,
        },
        {
          height: 10,
          id: 170,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 62,
          x: 5247,
          y: 741,
        },
        {
          height: 98,
          id: 171,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 10,
          x: 5247,
          y: 643,
        },
        {
          height: 10,
          id: 172,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 40,
          x: 4687,
          y: 591,
        },
        {
          height: 202,
          id: 173,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 11,
          x: 4716,
          y: 601,
        },
        {
          height: 82,
          id: 174,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 11,
          x: 4705,
          y: 793,
        },

        {
          height: 10,
          id: 175,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 29,
          x: 4687,
          y: 875,
        },
        {
          height: 123,
          id: 176,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 16,
          x: 4728,
          y: 1518,
        },
        {
          height: 16,
          id: 177,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 387,
          x: 4922,
          y: 1567,
        },
        {
          height: 10,
          id: 178,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 92,
          x: 5217,
          y: 1351,
        },
        {
          height: 10,
          id: 179,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 112,
          x: 5145,
          y: 1281,
        },
        {
          height: 10,
          id: 181,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 62,
          x: 5247,
          y: 1190,
        },
        {
          height: 81,
          id: 182,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 10,
          x: 5247,
          y: 1200,
        },
        {
          height: 60,
          id: 183,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 10,
          x: 5217,
          y: 1291,
        },
        {
          height: 10,
          id: 184,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 60,
          x: 3669,
          y: 1550,
        },
        {
          height: 10,
          id: 185,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 124,
          x: 3720,
          y: 1540,
        },
        {
          height: 33,
          id: 186,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 79,
          x: 3669,
          y: 1797,
        },
        {
          height: 10,
          id: 187,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 78,
          x: 4256,
          y: 1674,
        },
        {
          height: 10,
          id: 188,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 78,
          x: 4256,
          y: 1820,
        },
        {
          height: 136,
          id: 189,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 10,
          x: 4256,
          y: 1684,
        },
        {
          height: 10,
          id: 190,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 297,
          x: 4369,
          y: 1692,
        },
        {
          height: 10,
          id: 192,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 309,
          x: 4584,
          y: 1898,
        },

        {
          height: 50,
          id: 193,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 10,
          x: 4883,
          y: 1908,
        },
        {
          height: 10,
          id: 195,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 68,
          x: 4883,
          y: 1958,
        },
        {
          height: 10,
          id: 196,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 152,
          x: 4799,
          y: 1811,
        },
        {
          height: 77,
          id: 197,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 10,
          x: 4799,
          y: 1821,
        },
        {
          height: 177,
          id: 198,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 10,
          x: 2589,
          y: 2647,
        },
        {
          height: 10,
          id: 199,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 135,
          x: 2374,
          y: 2197,
        },
        {
          height: 10,
          id: 200,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 177,
          x: 2681,
          y: 2197,
        },
        {
          height: 10,
          id: 201,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 100,
          x: 3219,
          y: 2197,
        },
        {
          height: 56,
          id: 202,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 10,
          x: 2306,
          y: 2851,
        },
        {
          height: 56,
          id: 203,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 10,
          x: 3464,
          y: 2973,
        },
        {
          height: 86,
          id: 204,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 10,
          x: 3742,
          y: 2895,
        },
        {
          height: 10,
          id: 206,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 122,
          x: 3658,
          y: 3177,
        },
        {
          height: 10,
          id: 207,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 122,
          x: 2273,
          y: 3049,
        },
        {
          height: 137,
          id: 208,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 35,
          x: 2933,
          y: 3039,
        },
        {
          height: 137,
          id: 209,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 35,
          x: 3085,
          y: 3039,
        },
        {
          height: 92,
          id: 210,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 312,
          x: 2876,
          y: 2647,
        },

        {
          height: 15,
          id: 211,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 558,
          x: 3924,
          y: 2359,
        },
        {
          height: 303,
          id: 212,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 20,
          x: 4774,
          y: 2485,
        },
        {
          height: 407,
          id: 213,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 20,
          x: 4151,
          y: 2989,
        },
        {
          height: 103,
          id: 214,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 20,
          x: 3863,
          y: 2817,
        },
        {
          height: 288,
          id: 215,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 20,
          x: 4492,
          y: 2887,
        },
        {
          height: 178,
          id: 216,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 10,
          x: 4385,
          y: 3440,
        },
        {
          height: 10,
          id: 217,
          name: "",
          rotation: 0,
          class: "",
          visible: true,
          width: 122,
          x: 4106,
          y: 3736,
        },
      ],
      opacity: 1,
      class: "objectgroup",
      visible: true,
      x: 0,
      y: 0,
    },
    {
      draworder: "topdown",
      id: 9,
      name: "Theories",
      objects: [
        {
          height: 48,
          id: 236,
          name: "",
          rotation: 0,
          class: "i-1",
          visible: true,
          width: 104,
          x: 1930,
          y: 1901,
        },
        {
          height: 15,
          id: 238,
          name: "",
          rotation: 0,
          class: "i-2",
          visible: true,
          width: 50,
          x: 1273,
          y: 930,
        },
        {
          height: 15,
          id: 239,
          name: "",
          rotation: 0,
          class: "i-3",
          visible: true,
          width: 50,
          x: 2075,
          y: 930,
        },
        {
          height: 15,
          id: 240,
          name: "",
          rotation: 0,
          class: "i-4",
          visible: true,
          width: 50,
          x: 3771,
          y: 930,
        },
        {
          height: 15,
          id: 242,
          name: "",
          rotation: 0,
          class: "d-1",
          visible: true,
          width: 51,
          x: 3245,
          y: 2504,
        },
        {
          height: 40,
          id: 243,
          name: "",
          rotation: 0,
          class: "b-1",
          visible: true,
          width: 6,
          x: 2442,
          y: 1523,
        },
        {
          height: 40,
          id: 244,
          name: "",
          rotation: 0,
          class: "b-2",
          visible: true,
          width: 6,
          x: 2568,
          y: 1523,
        },
        {
          height: 40,
          id: 245,
          name: "",
          rotation: 0,
          class: "b-3",
          visible: true,
          width: 6,
          x: 2698,
          y: 1523,
        },
        {
          height: 40,
          id: 246,
          name: "",
          rotation: 0,
          class: "b-4",
          visible: true,
          width: 6,
          x: 2829,
          y: 1523,
        },
        {
          height: 40,
          id: 247,
          name: "",
          rotation: 0,
          class: "b-5",
          visible: true,
          width: 6,
          x: 2965,
          y: 1523,
        },
        {
          height: 40,
          id: 248,
          name: "",
          rotation: 0,
          class: "b-6",
          visible: true,
          width: 6,
          x: 3087,
          y: 1523,
        },
        {
          height: 40,
          id: 249,
          name: "",
          rotation: 0,
          class: "b-7",
          visible: true,
          width: 6,
          x: 3227,
          y: 1523,
        },
        {
          height: 40,
          id: 250,
          name: "",
          rotation: 0,
          class: "b-8",
          visible: true,
          width: 6,
          x: 3354,
          y: 1523,
        },
        {
          height: 40,
          id: 251,
          name: "",
          rotation: 0,
          class: "b-9",
          visible: true,
          width: 6,
          x: 3486,
          y: 1523,
        },
        {
          height: 40,
          id: 252,
          name: "",
          rotation: 0,
          class: "b-10",
          visible: true,
          width: 6,
          x: 3594,
          y: 1523,
        },
      ],
      opacity: 1,
      class: "objectgroup",
      visible: true,
      x: 0,
      y: 0,
    },
    {
      draworder: "topdown",
      id: 8,
      name: "Interactables",
      objects: [
        {
          height: 19,
          id: 219,
          name: "",
          rotation: 0,
          class: "1-a",
          visible: true,
          width: 85,
          x: 4598,
          y: 1706,
        },
        {
          height: 40,
          id: 220,
          name: "",
          rotation: 0,
          class: "1-b",
          visible: true,
          width: 69,
          x: 4069,
          y: 2380,
        },
        {
          height: 35,
          id: 221,
          name: "",
          rotation: 0,
          class: "1-c",
          visible: true,
          width: 177,
          x: 1577,
          y: 145,
        },
        {
          height: 45,
          id: 222,
          name: "",
          rotation: 0,
          class: "1-d",
          visible: true,
          width: 52,
          x: 4792,
          y: 1963,
        },
        {
          height: 69,
          id: 223,
          name: "",
          rotation: 0,
          class: "2-a",
          visible: true,
          width: 35,
          x: 4148,
          y: 3728,
        },
        {
          height: 34,
          id: 224,
          name: "",
          rotation: 0,
          class: "2-b",
          visible: true,
          width: 34,
          x: 4170,
          y: 1530,
        },
        {
          height: 35,
          id: 225,
          name: "",
          rotation: 0,
          class: "2-c",
          visible: true,
          width: 177,
          x: 766,
          y: 145,
        },
        {
          height: 35,
          id: 226,
          name: "",
          rotation: 0,
          class: "2-d",
          visible: true,
          width: 177,
          x: 3272,
          y: 145,
        },
        {
          height: 57,
          id: 227,
          name: "",
          rotation: 0,
          class: "2-e",
          visible: true,
          width: 90,
          x: 5132,
          y: 620,
        },
        {
          height: 35,
          id: 228,
          name: "",
          rotation: 0,
          class: "3-a",
          visible: true,
          width: 177,
          x: 2440,
          y: 145,
        },
        {
          height: 20,
          id: 229,
          name: "",
          rotation: 0,
          class: "3-b",
          visible: true,
          width: 20,
          x: 4467,
          y: 3052,
        },
        {
          height: 69,
          id: 230,
          name: "",
          rotation: 0,
          class: "4-a",
          visible: true,
          width: 35,
          x: 3703,
          y: 3169,
        },
        {
          height: 69,
          id: 231,
          name: "",
          rotation: 0,
          class: "5-a",
          visible: true,
          width: 35,
          x: 2315,
          y: 3041,
        },
        {
          height: 10,
          id: 232,
          name: "",
          rotation: 0,
          class: "5-b",
          visible: true,
          width: 15,
          x: 2971,
          y: 3160,
        },
        {
          height: 35,
          id: 233,
          name: "",
          rotation: 0,
          class: "5-c",
          visible: true,
          width: 177,
          x: 4109,
          y: 145,
        },
        {
          height: 79,
          id: 234,
          name: "",
          rotation: 0,
          class: "5-d",
          visible: true,
          width: 15,
          x: 4747,
          y: 1545,
        },

        {
          height: 48,
          id: 235,
          name: "",
          rotation: 0,
          class: "5-e",
          visible: true,
          width: 104,
          x: 1643,
          y: 2238,
        },
      ],
      opacity: 1,
      class: "objectgroup",
      visible: true,
      x: 0,
      y: 0,
    },
    {
      id: 12,
      layers: [
        {
          id: 33,
          name: "d-1",
          offsetx: 3214,
          offsety: 2476,
          opacity: 1,
          class: "imagelayer",
          visible: true,
          x: 0,
          y: 0,
        },
        {
          id: 37,
          name: "i-4",
          offsetx: 3740,
          offsety: 904,
          opacity: 1,
          class: "imagelayer",
          visible: true,
          x: 0,
          y: 0,
        },
        {
          id: 36,
          name: "i-3",
          offsetx: 2044,
          offsety: 904,
          opacity: 1,
          class: "imagelayer",
          visible: true,
          x: 0,
          y: 0,
        },
        {
          id: 35,
          name: "i-2",
          offsetx: 1241,
          offsety: 904,
          opacity: 1,
          class: "imagelayer",
          visible: true,
          x: 0,
          y: 0,
        },
        {
          id: 34,
          name: "i-1",
          offsetx: 1945,
          offsety: 1910,
          opacity: 1,
          class: "imagelayer",
          visible: true,
          x: 0,
          y: 0,
        },
        {
          id: 24,
          name: "b-10",
          offsetx: 3589,
          offsety: 1538,
          opacity: 1,
          class: "imagelayer",
          visible: true,
          x: 0,
          y: 0,
        },
        {
          id: 23,
          name: "b-9",
          offsetx: 3481,
          offsety: 1518,
          opacity: 1,
          class: "imagelayer",
          visible: true,
          x: 0,
          y: 0,
        },
        {
          id: 22,
          name: "b-8",
          offsetx: 3349,
          offsety: 1538,
          opacity: 1,
          class: "imagelayer",
          visible: true,
          x: 0,
          y: 0,
        },
        {
          id: 21,
          name: "b-7",
          offsetx: 3222,
          offsety: 1518,
          opacity: 1,
          class: "imagelayer",
          visible: true,
          x: 0,
          y: 0,
        },
        {
          id: 20,
          name: "b-6",
          offsetx: 3082,
          offsety: 1538,
          opacity: 1,
          class: "imagelayer",
          visible: true,
          x: 0,
          y: 0,
        },
        {
          id: 19,
          name: "b-5",
          offsetx: 2960,
          offsety: 1518,
          opacity: 1,
          class: "imagelayer",
          visible: true,
          x: 0,
          y: 0,
        },
        {
          id: 18,
          name: "b-4",
          offsetx: 2824,
          offsety: 1538,
          opacity: 1,
          class: "imagelayer",
          visible: true,
          x: 0,
          y: 0,
        },
        {
          id: 16,
          name: "b-3",
          offsetx: 2693,
          offsety: 1518,
          opacity: 1,
          class: "imagelayer",
          visible: true,
          x: 0,
          y: 0,
        },
        {
          id: 15,
          name: "b-2",
          offsetx: 2563,
          offsety: 1538,
          opacity: 1,
          class: "imagelayer",
          visible: true,
          x: 0,
          y: 0,
        },
        {
          id: 11,
          name: "b-1",
          offsetx: 2437,
          offsety: 1518,
          opacity: 1,
          class: "imagelayer",
          visible: true,
          x: 0,
          y: 0,
        },
      ],
      name: "TheorySprites",
      opacity: 1,
      class: "group",
      visible: true,
      x: 0,
      y: 0,
    },
    {
      id: 13,
      layers: [
        {
          id: 14,
          name: "1-a",
          offsetx: 4615,
          offsety: 1668,
          opacity: 1,
          class: "imagelayer",
          visible: true,
          x: 0,
          y: 0,
        },
        {
          id: 27,
          name: "1-b",
          offsetx: 4078,
          offsety: 2360,
          opacity: 1,
          class: "imagelayer",
          visible: true,
          x: 0,
          y: 0,
        },
        {
          id: 43,
          name: "1-c",
          offsetx: 1585,
          offsety: 108,
          opacity: 1,
          class: "imagelayer",
          visible: true,
          x: 0,
          y: 0,
        },
        {
          id: 25,
          name: "1-d",
          offsetx: 4792,
          offsety: 1969,
          opacity: 1,
          class: "imagelayer",
          visible: true,
          x: 0,
          y: 0,
        },
        {
          id: 29,
          name: "2-a",
          offsetx: 4101,
          offsety: 3745,
          opacity: 1,
          class: "imagelayer",
          visible: true,
          x: 0,
          y: 0,
        },
        {
          id: 26,
          name: "2-b",
          offsetx: 4162,
          offsety: 1517,
          opacity: 1,
          class: "imagelayer",
          visible: true,
          x: 0,
          y: 0,
        },
        {
          id: 42,
          name: "2-c",
          offsetx: 774,
          offsety: 108,
          opacity: 1,
          class: "imagelayer",
          visible: true,
          x: 0,
          y: 0,
        },
        {
          id: 45,
          name: "2-d",
          offsetx: 3280,
          offsety: 108,
          opacity: 1,
          class: "imagelayer",
          visible: true,
          x: 0,
          y: 0,
        },
        {
          id: 40,
          name: "2-e",
          offsetx: 5153,
          offsety: 629,
          opacity: 1,
          class: "imagelayer",
          visible: true,
          x: 0,
          y: 0,
        },
        {
          id: 44,
          name: "3-a",
          offsetx: 2448,
          offsety: 108,
          opacity: 1,
          class: "imagelayer",
          visible: true,
          x: 0,
          y: 0,
        },
        {
          id: 28,
          name: "3-b",
          offsetx: 4508,
          offsety: 3009,
          opacity: 1,
          class: "imagelayer",
          visible: true,
          x: 0,
          y: 0,
        },
        {
          id: 31,
          name: "4-a",
          offsetx: 3699,
          offsety: 3186,
          opacity: 1,
          class: "imagelayer",
          visible: true,
          x: 0,
          y: 0,
        },
        {
          id: 30,
          name: "5-a",
          offsetx: 2268,
          offsety: 3058,
          opacity: 1,
          class: "imagelayer",
          visible: true,
          x: 0,
          y: 0,
        },
        {
          id: 32,
          name: "5-b",
          offsetx: 2909,
          offsety: 3110,
          opacity: 1,
          class: "imagelayer",
          visible: true,
          x: 0,
          y: 0,
        },
        {
          id: 46,
          name: "5-c",
          offsetx: 4117,
          offsety: 108,
          opacity: 1,
          class: "imagelayer",
          visible: true,
          x: 0,
          y: 0,
        },
        {
          id: 41,
          name: "5-d",
          offsetx: 4686,
          offsety: 1502,
          opacity: 1,
          class: "imagelayer",
          visible: true,
          x: 0,
          y: 0,
        },

        {
          id: 38,
          name: "5-e",
          offsetx: 1658,
          offsety: 2248,
          opacity: 1,
          class: "imagelayer",
          visible: true,
          x: 0,
          y: 0,
        },
      ],
      name: "InteractableSprites",
      opacity: 1,
      class: "group",
      visible: true,
      x: 0,
      y: 0,
    },
  ],
  nextlayerid: 47,
  nextobjectid: 253,
  orientation: "orthogonal",
  renderorder: "right-down",
  tiledversion: "1.10.1",
  tileheight: 32,
  tilesets: [
    {
      firstgid: 1,
      source: "../../../Rbygghighres.tsx",
    },
  ],
  tilewidth: 32,
  class: "map",
  version: "1.10",
  width: 200,
});
